# 首页视频设置
vimeo:
  id: "103962647"
  color: "f05909" #默认是f05909
  image: "485925633"
  title: 2014Movie

# 网页设置
title: "ZE3kr"
language: en-us
defaultFileType: "video/mp4"
description: "ZE3kr’s video, photography, technology course, hot news discuss is on this website! Don't miss the newest post."
small-avatarurl: "http://i.vimeocdn.com/portrait/8171816_128x128.jpg"
avatarurl: "http://i.vimeocdn.com/portrait/8171816.jpg"
explicit: "no"
branch: master
copyright: CC BY-NC-SA 3.0.
copyright_link: http://creativecommons.org/licenses/by-nc-sa/3.0/
itunes: https://itunes.apple.com/podcast/id907999392?at=10lJIS

google_analytics: 
  enable: yes
  id: "UA-47292820-1"

index_page:
  photo: no
  video: yes

email: "ze3kr@icloud.com"
twitter_username: "ZE3kr"
# 建站设置
markdown: kramdown
permalink: pretty

# 屏蔽设置
blockitunes: "no"

# 插件
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# 页码设置
paginate: 10
paginate_path: "all/page/:num"

# 第三方评论窗
disqus: 
  enable: yes
  id: "ze3kr"

# 分享按钮
addthis: 
  enable: yes
  addthis_pubid: "ra-53c5146c23971c64"

facebook: 
  enable: yes
  layout: button_count
  show_faces: yes
  share: yes

twitter:
  enable: no
  appkey: ""

sinaweibo: 
  enable: yes
  ralateUid: "3026292980"
  appkey: "1963081010"

qzone:
  enable: yes
  showcount: "0" #不同于之前的，“showcount”填1代表“是”，填2代表“否”。

auto_hide: no
#根据地区自动隐藏（例如中国地区访问会隐藏Twitter和Facebook。
