# 首页视频设置
vimeo:
  id: "103962647"
  color: "f05909" #默认是f05909
  image: "485925633"
  title: 2014Movie

# 网页设置
title: "ZE3kr"
language: en-us
defaultFileType: "video/mp4"
description: "ZE3kr’s video, photography, technology course, hot news discuss is on this website! Don't miss the newest post."
small-avatarurl: "https://technolumn.b0.upaiyun.com/thrideo/ze3kr_s.jpg"
avatarurl: "https://technolumn.b0.upaiyun.com/thrideo/ze3kr.jpg"
explicit: "no"
branch: master
copyright: CC BY-NC-SA 3.0.
copyright_link: https://creativecommons.org/licenses/by-nc-sa/3.0/
itunes: https://itunes.apple.com/podcast/id907999392?at=10lJIS

file-server-domain: "//ze3kr.com/" #也可以是http://ze3file.b0.upaiyun.com/

google_analytics: 
  enable: yes
  id: "UA-47292820-1"

index_page:
  photo: no
  video: yes

email: "admin@ze3kr.com"
twitter_username: "ZE3kr"
# 建站设置
markdown: kramdown
permalink: pretty

# 屏蔽设置
blockitunes: "no"

# 插件
gems:
- jekyll-redirect-from
- jekyll-sitemap

# 页码设置
paginate: 10
paginate_path: "all/page/:num"

# 第三方评论窗
disqus: 
  enable: yes
  id: "ze3kr"

# 分享按钮
addthis: 
  enable: yes
  addthis_pubid: "ra-53c5146c23971c64"
